---
repos:
  - hooks:
      - id: trailing-whitespace
        stages: [commit]
      - id: check-ast
        stages: [commit]
      - id: check-merge-conflict
        stages: [commit]
      - id: debug-statements
        stages: [commit]
      - id: end-of-file-fixer
        stages: [commit]
      - args: [ '--fix=no' ]
        id: mixed-line-ending
        stages: [commit]
    repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v3.2.0


  - hooks:
      - id: black
        stages: [commit]
        language_version: python3.9
        additional_dependencies: ['click==8.0.4']  # Why: https://github.com/psf/black/issues/2964
    repo: https://github.com/ambv/black
    rev: 21.7b0


  - hooks:
      - id: isort
        stages: [commit]
    repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.6.4


  - repo: local
    hooks:
      - id: pytest
        stages: [manual]
        name: pytest
        entry: make tests
        language: system
        pass_filenames: false

  - repo: local
    hooks:
        # Why: https://pylint.pycqa.org/en/stable/user_guide/installation/pre-commit-integration.html
      - id: pylint
        stages: [commit]
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
              "--rcfile=pyproject.toml"
          ]
